from pkg_resources import DistributionNotFound, get_distribution

try:
    VERSION = get_distribution(__name__).version
except DistributionNotFound:
    try:
        from ._version import version as VERSION
    except ImportError:
        msg = "Failed to find autogenerated _version.py."
        raise ImportError(msg) from None
__version__ = VERSION
