pipeline {
    agent { label "!(scout-ci7 || scout-ci)"}

    stages {
        stage('Suggest') {
            steps {
                withCredentials([usernamePassword(credentialsId: "${env.GITHUB_CREDENTIAL}", usernameVariable: 'GH_USER', passwordVariable: 'GITHUB_TOKEN')]) {
                    sh """
                        source /project/res/SDP_bashrc
                        virtualenv env
                        source env/bin/activate
                        pip install .
                    """
                    script {
                        env.PR_URL = sh(
                            returnStdout: true,
                                script: "source env/bin/activate; komodo-suggest-symlinks --git-fork ${env.GIT_FORK} --git-repo ${env.GIT_REPO} --git-ref ${env.GIT_REF} ${env.RELEASE} ${env.MODE} ${env.BUILD_URL} ${env.JOB_NAME}"
                            ).trim()
                    }
                    slackSend color: "#2f993a", message: """Suggested new symlink (${env.RELEASE} - ${env.MODE}): (<${env.PR_URL}|Open>)"""
                }
            }
        }
    }
}
