name: Style

on:
 push:
   branches:
     - main
     - 'version-**'
 pull_request:

jobs:
  check-style:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install ".[dev]"

    - name: Run mypy
      run: |
        mypy komodo

    - name: Run black
      uses: psf/black@stable

    - name: Lint with ruff
      run: |
        ruff check komodo tests

    - name: pylint
      run: |
        pylint komodo tests
